### ISSUE TITLE
Wanna ipfsify?

### ISSUE THREAD

**Issue by faddat** [c29r3/cosmos-snapshots#1]
Hi, I am operating an IPFS cluster. 

I've used your snapshots many times.  

Do you want to team up so we can distribute these faster?

**Comment by c29r3** [comment]
> Hi, I am operating an IPFS cluster.
> 
> I've used your snapshots many times.
> 
> Do you want to team up so we can distribute these faster?

Sorry for the long answer 😅. Yes, of course that's a good idea. We can discuss this on telegram - https://t.me/go_on
