### ISSUE TITLE
How you did statesync for Akash

### ISSUE THREAD

**Issue by kucharskim** [c29r3/cosmos-snapshots#17]
For my statesync fails all the time, after multiple tries, how did you do it?

Reference https://github.com/c29r3/cosmos-snapshots/commit/97a7992c1806d7c5e17f1752bb92c393b3488ab4

**Comment by kucharskim** [comment]
I'm on `v0.12.2`

**Comment by c29r3** [comment]
https://github.com/ovrclk/akash/issues/1503

**Comment by kucharskim** [comment]
Thanks!
